/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * TS counterpart of adk-python
 * contributing/samples/patterns/context_offloading_with_artifact.
 *
 * Sales Data Assistant Agent demonstrating context offloading with artifacts.
 * Tool names, parameter names, artifact names, metadata keys and instruction
 * text are unchanged; the mock report is generated by the same recipe (random
 * revenue/units plus 500 sub-region lines), so it is large on both sides and
 * random on both sides.
 *
 * Three API differences, all of them worked around rather than papered over:
 *
 *  1. `LoadArtifactsTool._append_artifacts_to_llm_request` is a protected
 *     override point in adk-python. In adk-js the same step is
 *     `private appendArtifactsToLlmRequest` (core/src/tools/load_artifacts_tool.ts),
 *     so a subclass cannot replace just that half. `processLlmRequest` is
 *     overridden instead and `BaseTool`'s half invoked directly, which
 *     reproduces the Python control flow exactly.
 *  2. `ToolContext.save_artifact(..., custom_metadata=...)` has no adk-js
 *     equivalent: `Context.saveArtifact(filename, artifact)` takes no
 *     metadata and there is no `Context.getArtifactVersion`. The underlying
 *     `SessionArtifactService` does support both, so the tool goes through
 *     `toolContext.invocationContext.artifactService` and records the artifact
 *     delta by hand — the one line `Context.saveArtifact` would have done.
 *  3. `LlmRequest.append_instructions()` is a method in adk-python; in adk-js
 *     `appendInstructions` is a free function in
 *     core/src/models/llm_request.ts that is *not* re-exported from
 *     `@google/adk`, so it is inlined below.
 */
import type {Context, LlmRequest, ToolProcessLlmRequest} from '@google/adk';
import {BaseTool, FunctionTool, LlmAgent, LoadArtifactsTool} from '@google/adk';
import type {Part} from '@google/genai';
import {HarmBlockThreshold, HarmCategory} from '@google/genai';
import {z} from 'zod';

import {PARITY_MODEL} from '../model.ts';

/** adk-js keeps `appendInstructions` internal; this is the same operation. */
function appendInstructions(llmRequest: LlmRequest, instructions: string[]) {
  llmRequest.config ??= {};
  const newInstructions = instructions.join('\n\n');
  llmRequest.config.systemInstruction = llmRequest.config.systemInstruction
    ? `${llmRequest.config.systemInstruction}\n\n${newInstructions}`
    : newInstructions;
}

/** The function response on the last content, if the last content has one. */
function lastFunctionResponse(llmRequest: LlmRequest) {
  const parts = llmRequest.contents?.at(-1)?.parts;
  return parts?.length ? parts[0].functionResponse : undefined;
}

/**
 * A custom tool to load artifacts that also provides summaries.
 *
 * This tool extends LoadArtifactsTool to read custom metadata from artifacts
 * and provide summaries to the LLM in the system instructions, allowing the
 * model to know what artifacts are available (e.g., "Sales report for APAC").
 * It also injects artifact content into the LLM request when load_artifacts
 * is called by the model.
 */
class CustomLoadArtifactsTool extends LoadArtifactsTool {
  override async processLlmRequest(
    request: ToolProcessLlmRequest,
  ): Promise<void> {
    // Python overrides `_append_artifacts_to_llm_request`, leaving
    // `LoadArtifactsTool.process_llm_request` in place. adk-js keeps that step
    // private, so the base declaration half is called directly and the append
    // half replaced wholesale.
    await BaseTool.prototype.processLlmRequest.call(this, request);
    await this.appendArtifactsWithSummaries(request);
  }

  private async appendArtifactsWithSummaries({
    toolContext,
    llmRequest,
  }: ToolProcessLlmRequest): Promise<void> {
    const artifactService = toolContext.invocationContext.artifactService;
    if (!artifactService) {
      return;
    }
    const artifactNames = await toolContext.listArtifacts();
    if (!artifactNames.length) {
      return;
    }

    const summaries = new Map<string, unknown>();
    for (const name of artifactNames) {
      const versionInfo = await artifactService.getArtifactVersion({
        filename: name,
      });
      if (versionInfo?.customMetadata) {
        summaries.set(name, versionInfo.customMetadata['summary']);
      }
    }

    const artifactsWithSummaries = artifactNames.map((name) =>
      summaries.get(name) ? `${name}: ${summaries.get(name)}` : name,
    );

    // Tell the model about the available artifacts.
    appendInstructions(llmRequest, [
      `You have access to artifacts: ${JSON.stringify(artifactsWithSummaries)}.
If you need to answer a question that requires artifact content, first check if
the content was very recently added to the conversation (e.g., in the last
turn). If it is, use that content directly to answer. If the content is not
available in the recent conversation history, you MUST call \`load_artifacts\`
to retrieve it before answering.
`,
    ]);

    // Attach the content of the artifacts if the model requests them.
    // This only adds the content to the model request, instead of the session.
    const functionResponse = lastFunctionResponse(llmRequest);
    if (!functionResponse || functionResponse.name !== 'load_artifacts') {
      return;
    }
    const response = (functionResponse.response ?? {}) as {
      artifact_names?: string[];
    };
    const requested = response.artifact_names ?? [];
    if (!requested.length) {
      return;
    }
    for (const artifactName of requested) {
      // Try session-scoped first (default behavior)
      let artifact: Part | undefined =
        await toolContext.loadArtifact(artifactName);

      // If not found and name doesn't already have user: prefix,
      // try cross-session artifacts with user: prefix
      if (artifact === undefined && !artifactName.startsWith('user:')) {
        artifact = await toolContext.loadArtifact(`user:${artifactName}`);
      }

      if (artifact === undefined) {
        console.warn(`Artifact "${artifactName}" not found, skipping`);
        continue;
      }
      llmRequest.contents.push({
        role: 'user',
        parts: [{text: `Artifact ${artifactName} is:`}, artifact],
      });
    }
  }
}

const queryLargeDataParameters = z.object({
  query: z
    .string()
    .describe('The user query, expected to contain a region name.'),
});

/**
 * Generates a mock sales report for a given region and saves it as an
 * artifact.
 */
async function queryLargeData(
  {query}: {query: string},
  toolContext?: Context,
): Promise<{message: string; artifact_name: string | null}> {
  let region = 'Unknown';
  const lowered = query.toLowerCase();
  if (lowered.includes('north america')) {
    region = 'North America';
  } else if (lowered.includes('emea')) {
    region = 'EMEA';
  } else if (lowered.includes('apac')) {
    region = 'APAC';
  } else {
    return {
      message: `Sorry, I don't have data for query: ${query}`,
      artifact_name: null,
    };
  }

  // simulate large data - Generate a mock sales report
  const revenue = (500 + Math.random() * 1500).toFixed(2);
  const units = Math.floor(Math.random() * 400001) + 100000;
  let reportContent = `SALES REPORT: ${region} Q3 2025
=========================================
Total Revenue: $${revenue}M
Units Sold: ${units}
Key Products: Gadget Pro, Widget Max, Thingy Plus
Highlights:
- Strong growth in Gadget Pro driven by new marketing campaign.
- Widget Max sales are stable.
- Thingy Plus saw a 15% increase in market share.

Regional Breakdown:
`;
  for (let i = 0; i < 500; i++) {
    reportContent += `Sub-region ${i + 1} performance metric: ${(
      Math.random() * 100
    ).toFixed(2)}\n`;
  }
  const dataSummary = `Sales report for ${region} Q3 2025`;
  const artifactName = `${region.split(' ').join('_')}_sales_report_q3_2025.txt`;

  const artifactService = toolContext?.invocationContext.artifactService;
  if (!artifactService) {
    throw new Error('Artifact service is not initialized.');
  }
  // `Context.saveArtifact` cannot carry custom metadata, so the service is
  // called directly and the artifact delta recorded the way it would.
  const version = await artifactService.saveArtifact({
    filename: artifactName,
    artifact: {text: reportContent},
    customMetadata: {summary: dataSummary},
  });
  toolContext.eventActions.artifactDelta[artifactName] = version;

  return {
    message:
      `Sales data for ${region} for Q3 2025 is saved as artifact` +
      ` '${artifactName}'.`,
    artifact_name: artifactName,
  };
}

/**
 * A tool that queries large data and saves it as an artifact.
 *
 * This tool wraps the query_large_data function. Its processLlmRequest method
 * checks if query_large_data was just called. If so, it loads the artifact
 * that was just created and injects its content into the LLM request, so the
 * model can use the data immediately in the next turn.
 */
class QueryLargeDataTool extends FunctionTool<typeof queryLargeDataParameters> {
  constructor() {
    super({
      name: 'query_large_data',
      description: `Generates a mock sales report for a given region and saves it as an artifact.

This function simulates querying a large dataset. It generates a mock report
for North America, EMEA, or APAC, saves it as a text artifact, and includes
a data summary in the artifact's custom metadata.
Example queries: "Get sales data for North America", "EMEA sales report".`,
      parameters: queryLargeDataParameters,
      execute: queryLargeData,
    });
  }

  override async processLlmRequest(
    request: ToolProcessLlmRequest,
  ): Promise<void> {
    await super.processLlmRequest(request);
    const functionResponse = lastFunctionResponse(request.llmRequest);
    if (!functionResponse || functionResponse.name !== 'query_large_data') {
      return;
    }
    const response = (functionResponse.response ?? {}) as {
      artifact_name?: string;
    };
    const artifactName = response.artifact_name;
    if (!artifactName) {
      return;
    }
    const artifact = await request.toolContext.loadArtifact(artifactName);
    if (artifact) {
      request.llmRequest.contents.push({
        role: 'user',
        parts: [{text: `Artifact ${artifactName} is:`}, artifact],
      });
    }
  }
}

export const rootAgent = new LlmAgent({
  name: 'context_offloading_with_artifact',
  model: PARITY_MODEL,
  description: 'An assistant for querying large sales reports.',
  instruction: `
      You are a sales data assistant. You can query large sales reports by
      region (North America, EMEA, APAC) using the query_large_data tool.
      If you are asked to compare data between regions, make sure you have
      queried the data for all required regions first, and then use the
      load_artifacts tool if you need to access reports from previous turns.
    `,
  tools: [new QueryLargeDataTool(), new CustomLoadArtifactsTool()],
  generateContentConfig: {
    safetySettings: [
      {
        // avoid false alarm about rolling dice.
        category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
        threshold: HarmBlockThreshold.OFF,
      },
    ],
  },
});
