/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import {GoogleAuth} from 'google-auth-library';
import {experimental} from '../utils/experimental.js';
import {guessMimeType} from '../utils/file_utils.js';
import {logger} from '../utils/logger.js';
import {BaseCodeExecutor, ExecuteCodeParams} from './base_code_executor.js';
import {CodeExecutionResult, File} from './code_execution_utils.js';

const CLOUD_PLATFORM_SCOPE = 'https://www.googleapis.com/auth/cloud-platform';
const CODE_INTERPRETER_EXTENSION_ENV = 'CODE_INTERPRETER_EXTENSION_NAME';

/**
 * Public prebuilt Code Interpreter manifest used to provision a new extension
 * from the hub.
 */
const CODE_INTERPRETER_MANIFEST_URI =
  'gs://vertex-extension-public/code_interpreter.yaml';

const EXTENSION_RESOURCE_PATTERN =
  /^projects\/[^/]+\/locations\/([^/]+)\/extensions\/[^/]+$/;

const DEFAULT_IMPORT_MAX_ATTEMPTS = 180;
const IMPORT_POLL_INTERVAL_MS = 1000;

/**
 * Output file extensions promoted to an `image/<ext>` MIME type, matching the
 * canonical adk-python `VertexAiCodeExecutor`.
 *
 * The promotion is deliberately non-normalized: a `.jpg` becomes `image/jpg`,
 * not the registered `image/jpeg`, because adk-python emits
 * `f'image/{file_type}'` and the two SDKs should report the same MIME type for
 * the same executed code. This differs on purpose from `guessMimeType`, the
 * fallback used below, which maps `jpg` to `image/jpeg`.
 */
const SUPPORTED_IMAGE_TYPES = ['png', 'jpg', 'jpeg'];

/**
 * Output file extensions promoted to a `text/<ext>` MIME type, matching the
 * canonical adk-python `VertexAiCodeExecutor`.
 */
const SUPPORTED_DATA_FILE_TYPES = ['csv'];

/**
 * Python preamble prepended to every executed code block. Ported verbatim from
 * the adk-python `VertexAiCodeExecutor` (the Code Interpreter runs Python, so
 * the preamble stays Python).
 */
const IMPORTED_LIBRARIES = `
import io
import math
import re

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy

def crop(s: str, max_chars: int = 64) -> str:
  """Crops a string to max_chars characters."""
  return s[: max_chars - 3] + '...' if len(s) > max_chars else s


def explore_df(df: pd.DataFrame) -> None:
  """Prints some information about a pandas DataFrame."""

  with pd.option_context(
      'display.max_columns', None, 'display.expand_frame_repr', False
  ):
    # Print the column names to never encounter KeyError when selecting one.
    df_dtypes = df.dtypes

    # Obtain information about data types and missing values.
    df_nulls = (len(df) - df.isnull().sum()).apply(
        lambda x: f'{x} / {df.shape[0]} non-null'
    )

    # Explore unique total values in columns using \`.unique()\`.
    df_unique_count = df.apply(lambda x: len(x.unique()))

    # Explore unique values in columns using \`.unique()\`.
    df_unique = df.apply(lambda x: crop(str(list(x.unique()))))

    df_info = pd.concat(
        (
            df_dtypes.rename('Dtype'),
            df_nulls.rename('Non-Null Count'),
            df_unique_count.rename('Unique Values Count'),
            df_unique.rename('Unique Values'),
        ),
        axis=1,
    )
    df_info.index.name = 'Columns'
    print(f"""Total rows: {df.shape[0]}
Total columns: {df.shape[1]}

{df_info}""")
`;

/**
 * A single output/input file exchanged with the Code Interpreter extension. The
 * extension returns file contents base64-encoded.
 */
export interface ExtensionFile {
  name: string;
  contents: string;
}

/**
 * Parameters for the Code Interpreter extension `execute` operation.
 */
export interface ExtensionExecuteParams {
  /** The Python code to execute. */
  code: string;
  /** Input files made available to the code. */
  files?: ExtensionFile[];
  /** Session id used to persist state across executions. */
  sessionId?: string;
}

/**
 * The result of a Code Interpreter extension `execute` operation, matching the
 * fields returned by the extension.
 */
export interface ExtensionExecuteResponse {
  /** Standard output of the execution. */
  execution_result?: string;
  /** Standard error of the execution. */
  execution_error?: string;
  /** Files generated by the execution. */
  output_files?: ExtensionFile[];
}

/**
 * Minimal client contract for the managed Vertex AI Code Interpreter extension.
 * Injectable so tests can substitute a fake for the REST-backed default.
 */
export interface CodeInterpreterExtensionClient {
  /**
   * Creates a Code Interpreter extension from the public hub and returns its
   * resource name.
   */
  importFromHub(projectId: string, location: string): Promise<string>;
  /** Runs the extension's `execute` operation and returns the parsed result. */
  execute(
    resourceName: string,
    params: ExtensionExecuteParams,
  ): Promise<ExtensionExecuteResponse>;
}

/**
 * Options for VertexAiCodeExecutor.
 */
export interface VertexAiCodeExecutorOptions {
  /**
   * If set, load this existing Code Interpreter extension instead of creating a
   * new one. Format:
   * projects/<project>/locations/<location>/extensions/<id>
   *
   * Rejected by the constructor if it does not match that format.
   */
  resourceName?: string;

  /**
   * Project ID. Defaults to GOOGLE_CLOUD_PROJECT. Required unless a
   * `resourceName` is configured, since creating an extension from the hub
   * needs one.
   */
  projectId?: string;

  /**
   * Location. Defaults to GOOGLE_CLOUD_LOCATION, then 'us-central1'. Ignored
   * when a `resourceName` is configured: that extension's own region is used.
   */
  location?: string;

  /**
   * Injectable extension client, primarily for testing. If omitted, a default
   * REST-backed client (GoogleAuth + fetch) is created.
   */
  client?: CodeInterpreterExtensionClient;
}

/** The Vertex AI regional endpoint base URL for extensions. */
function regionalEndpoint(location: string): string {
  return `https://${location}-aiplatform.googleapis.com/v1beta1`;
}

/** Extracts the location component from an extension resource name. */
function locationFromResourceName(resourceName: string): string {
  const match = resourceName.match(EXTENSION_RESOURCE_PATTERN);
  if (!match) {
    throw new Error(
      `Invalid code interpreter extension resource name: ${resourceName}`,
    );
  }
  return match[1];
}

/** Prepends the imported-library preamble to a user code block. */
function getCodeWithImports(code: string): string {
  return `\n${IMPORTED_LIBRARIES}\n\n${code}\n`;
}

/** Maps an extension output file to a `File`, applying the MIME type rules. */
function mapOutputFileToFile(outputFile: ExtensionFile): File {
  const parts = outputFile.name.split('.');
  const fileType = parts[parts.length - 1];
  let mimeType: string;
  if (SUPPORTED_IMAGE_TYPES.includes(fileType)) {
    mimeType = `image/${fileType}`;
  } else if (SUPPORTED_DATA_FILE_TYPES.includes(fileType)) {
    mimeType = `text/${fileType}`;
  } else {
    mimeType = guessMimeType(outputFile.name);
  }
  return {
    name: outputFile.name,
    content: outputFile.contents,
    mimeType,
  };
}

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/** A long-running operation returned by the extensions:import endpoint. */
interface ExtensionImportOperation {
  name?: string;
  done?: boolean;
  /** Set instead of `response` when the operation finishes unsuccessfully. */
  error?: {code?: number; message?: string};
  response?: {name: string};
}

/**
 * Default REST-backed {@link CodeInterpreterExtensionClient} using Application
 * Default Credentials (`GoogleAuth`) and `fetch`, following the approach used by
 * other Vertex-backed adk-js services.
 */
class DefaultCodeInterpreterExtensionClient implements CodeInterpreterExtensionClient {
  private readonly auth = new GoogleAuth({scopes: [CLOUD_PLATFORM_SCOPE]});

  async importFromHub(projectId: string, location: string): Promise<string> {
    const endpoint = regionalEndpoint(location);
    const importUrl = `${endpoint}/projects/${projectId}/locations/${location}/extensions:import`;
    let operation = await this.request<ExtensionImportOperation>(importUrl, {
      method: 'POST',
      body: {
        displayName: 'Code Interpreter',
        description:
          'This extension generates and executes code in the specified language',
        manifest: {
          name: 'code_interpreter_tool',
          description: 'Google Code Interpreter Extension',
          apiSpec: {openApiGcsUri: CODE_INTERPRETER_MANIFEST_URI},
          authConfig: {
            authType: 'GOOGLE_SERVICE_ACCOUNT_AUTH',
            googleServiceAccountConfig: {},
          },
        },
      },
    });

    let attempts = 0;
    while (!operation.done && attempts < DEFAULT_IMPORT_MAX_ATTEMPTS) {
      await delay(IMPORT_POLL_INTERVAL_MS);
      operation = await this.request<ExtensionImportOperation>(
        `${endpoint}/${operation.name}`,
        {method: 'GET'},
      );
      attempts++;
    }

    if (!operation.done) {
      throw new Error(
        `Code Interpreter extension creation operation ${operation.name} did not complete in time.`,
      );
    }
    // A `done` operation carries either a response or an error, never both, so
    // surface the failure instead of dereferencing an absent response.
    if (operation.error || !operation.response) {
      throw new Error(
        `Code Interpreter extension creation failed: ${
          operation.error?.message ?? 'operation returned no response'
        }`,
      );
    }

    return operation.response.name;
  }

  async execute(
    resourceName: string,
    params: ExtensionExecuteParams,
  ): Promise<ExtensionExecuteResponse> {
    const endpoint = regionalEndpoint(locationFromResourceName(resourceName));
    const operationParams: Record<string, unknown> = {code: params.code};
    if (params.files) {
      operationParams['files'] = params.files;
    }
    if (params.sessionId) {
      operationParams['session_id'] = params.sessionId;
    }

    const response = await this.request<{content: string}>(
      `${endpoint}/${resourceName}:execute`,
      {method: 'POST', body: {operationId: 'execute', operationParams}},
    );
    return JSON.parse(response.content) as ExtensionExecuteResponse;
  }

  private async request<T>(
    url: string,
    init: {method: string; body?: unknown},
  ): Promise<T> {
    const headers = await this.authorizedHeaders();
    const response = await fetch(url, {
      method: init.method,
      headers,
      body: init.body === undefined ? undefined : JSON.stringify(init.body),
    });
    if (!response.ok) {
      const text = await response.text();
      throw new Error(
        `API request failed with status ${response.status}: ${text}`,
      );
    }
    return (await response.json()) as T;
  }

  private async authorizedHeaders(): Promise<Headers> {
    const client = await this.auth.getClient();
    const headers = await client.getRequestHeaders();
    headers.set('Content-Type', 'application/json');
    return headers;
  }
}

/**
 * A code executor that uses the managed Vertex AI Code Interpreter Extension to
 * execute model-generated Python code, returning stdout, stderr, and generated
 * output files (images and data files).
 */
@experimental
export class VertexAiCodeExecutor extends BaseCodeExecutor {
  /**
   * The resource name of the Code Interpreter extension. Format:
   * projects/<project>/locations/<location>/extensions/<id>
   */
  resourceName?: string;
  private projectId?: string;
  private location: string;
  private client: CodeInterpreterExtensionClient;
  private resourceNamePromise?: Promise<string>;

  constructor(options: VertexAiCodeExecutorOptions = {}) {
    super();
    // Deliberate divergence from adk-python, which leaves both at the
    // BaseCodeExecutor defaults. `stateful` is required for getOrSetExecutionId()
    // to populate executionId — session reuse is the point of this executor.
    // `optimizeDataFile` opts into the CSV data-file extraction that the pandas
    // preamble below is built for.
    this.stateful = true;
    this.optimizeDataFile = true;

    this.resourceName =
      options.resourceName || process.env[CODE_INTERPRETER_EXTENSION_ENV];
    this.projectId = options.projectId || process.env.GOOGLE_CLOUD_PROJECT;
    // A configured extension pins its own region, so derive the location from it
    // rather than from the options/environment. This also rejects a malformed
    // resource name here instead of mid agent-run on the first executeCode().
    this.location = this.resourceName
      ? locationFromResourceName(this.resourceName)
      : options.location || process.env.GOOGLE_CLOUD_LOCATION || 'us-central1';

    // Needed by getResourceName() whether or not the client is injected.
    if (!this.resourceName && !this.projectId) {
      throw new Error('Project ID is required.');
    }
    this.client = options.client ?? new DefaultCodeInterpreterExtensionClient();
  }

  override async executeCode(
    params: ExecuteCodeParams,
  ): Promise<CodeExecutionResult> {
    const {codeExecutionInput} = params;
    const resourceName = await this.getResourceName();

    const executeParams: ExtensionExecuteParams = {
      code: getCodeWithImports(codeExecutionInput.code),
    };
    if (codeExecutionInput.inputFiles.length > 0) {
      executeParams.files = codeExecutionInput.inputFiles.map((file) => ({
        name: file.name,
        contents: file.content,
      }));
    }
    if (codeExecutionInput.executionId) {
      executeParams.sessionId = codeExecutionInput.executionId;
    }

    const response = await this.client.execute(resourceName, executeParams);

    return {
      stdout: response.execution_result ?? '',
      stderr: response.execution_error ?? '',
      outputFiles: (response.output_files ?? []).map(mapOutputFileToFile),
    };
  }

  /**
   * Resolves the extension resource name, creating one from the hub on first use
   * when neither an explicit resource name nor the environment variable is set.
   * The created name is memoized and written back to the environment for reuse.
   */
  private async getResourceName(): Promise<string> {
    if (this.resourceName) {
      return this.resourceName;
    }

    // The constructor rejects this combination, but `resourceName` is public and
    // mutable, so re-check rather than assert it away.
    const projectId = this.projectId;
    if (!projectId) {
      throw new Error('Project ID is required.');
    }

    if (!this.resourceNamePromise) {
      this.resourceNamePromise = (async () => {
        logger.debug(
          'No Code Interpreter extension configured. Creating a new one from the hub...',
        );
        const created = await this.client.importFromHub(
          projectId,
          this.location,
        );
        process.env[CODE_INTERPRETER_EXTENSION_ENV] = created;
        this.resourceName = created;
        return created;
      })();
    }

    return this.resourceNamePromise;
  }
}
