name: validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_OPTIONS: "--max-old-space-size=8192"

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: npm install

      - name: Check for secrets leaks
        run: npx secretlint "**/*"

      - name: Build packages
        run: npm run build

      - name: Run type check
        run: npm run ts:check

      - name: Type check samples
        run: npm run ts:check:samples

      - name: Run tests and check code coverage
        run: npm run test:coverage

      - name: Run lint check
        run: npm run lint

      - name: Run format check
        run: npm run format:check

      - name: Run documentation build check
        run: npm run docs:check
